version: '3.7'

services:

  sample:
    container_name: meltdownspectreapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/Users/StephanSchiller/Documents/Dockerprojekte/dockervolumes/meltspecapp'
      - '/Users/StephanSchiller/Documents/Dockerprojekte/dockervolumes/meltspecapp/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
